// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh8KtXIGnHlI0ykUjY3rKFpTIDpLrra9c',
    appId: '1:677857731211:web:ef60be0b7f42325ccbaa8e',
    messagingSenderId: '677857731211',
    projectId: 'multimedia-telltales',
    authDomain: 'multimedia-telltales.firebaseapp.com',
    storageBucket: 'multimedia-telltales.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRBSuy6iJbqPSbcRogFCepgDVUSAqrUlg',
    appId: '1:677857731211:android:275f347e9e0e008fcbaa8e',
    messagingSenderId: '677857731211',
    projectId: 'multimedia-telltales',
    storageBucket: 'multimedia-telltales.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe8rCedSwDrIRiBLQoWYvawb4Xv4zxDAQ',
    appId: '1:677857731211:ios:24e0ba87ccf6738fcbaa8e',
    messagingSenderId: '677857731211',
    projectId: 'multimedia-telltales',
    storageBucket: 'multimedia-telltales.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe8rCedSwDrIRiBLQoWYvawb4Xv4zxDAQ',
    appId: '1:677857731211:ios:24e0ba87ccf6738fcbaa8e',
    messagingSenderId: '677857731211',
    projectId: 'multimedia-telltales',
    storageBucket: 'multimedia-telltales.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh8KtXIGnHlI0ykUjY3rKFpTIDpLrra9c',
    appId: '1:677857731211:web:d0c2f854b448194dcbaa8e',
    messagingSenderId: '677857731211',
    projectId: 'multimedia-telltales',
    authDomain: 'multimedia-telltales.firebaseapp.com',
    storageBucket: 'multimedia-telltales.appspot.com',
  );

}